### ISSUE TITLE
Comparison to the ipnetwork crate?

### ISSUE THREAD

**Issue by ghost** [krisprice/ipnet#17]
Would it be possible to get a short line in the readme with a comparison to the [ipnetwork](https://crates.io/crates/ipnetwork) crate please?

I was looking at both seem pretty similar on the surface so I was curious of any deeper items that may be different.

Thank you for the hard work on this library!

**Comment by krisprice** [comment]
Hi @evitalis - I haven't done a comparison but you're welcome to compare them. :-) Not sure of the current status, but at the time `ipnetwork` was incomplete and required the Rust nightly toolchain. I wanted an implementation that worked with the stable toolchain, included IPv6 types, and that aligned with the Rust internal IpAddr types, and was oriented more to network programming.

**Comment by ghost** [comment]
Hi @krisprice , sorry I didn't get back to this. What you said makes sense and I will likely be going with `ipnet` (this library) for my current project.
