### ISSUE TITLE
IpNet.hosts() returns wrong number of hosts.

### ISSUE THREAD

**Issue by ehelbig1** [krisprice/ipnet#27]
Given the CIDR 1.1.1.1/30 I would expect to get back the hosts:
1.1.1.0
1.1.1.1
1.1.1.2
1.1.1.3

But I only get back these hosts:
1.1.1.1
1.1.1.2

`
let cidr = IpNet::from_str("1.1.1.1/30").unwrap();
for host in cidr.hosts() {
    println!("{}", host);
}
`

**Comment by ehelbig1** [comment]
oh, I think I see what's happening. For any cidr with a suffix less than 31 the first ip and broadcast ip are being removed. It does feel a little strange that there's not uniformed functionality. Should the consumer of this library decide if they want to ignore these two ips?

**Comment by krisprice** [comment]
Hi @ehelbig1 - yep hosts() returns just valid host addresses, for IPv4 the first and last are usually the nonassignable "network" and "broadcast" addresses. For /31s the rule changes and they become assignable as an address space conserving measure for point to point links. It seems like there's a desire for an all_addresses() like method that includes the broadcast and network addresses. Can I ask how you're using it?

**Comment by ehelbig1** [comment]
I'm working on some network exploration tools and iterating through hosts from a given cidr address. Thank for the additional information, obviously I have a bit more research to do into cidr addresses 😛. I don't have an immediate need for the all_addresses() functionality. It doesn't sound like a common use case and can always be calculated off other information.

Thank you,
Evan
