### ISSUE TITLE
Allow creation of const items of type IpvXNet

### ISSUE THREAD

**Issue by jjanowsk** [krisprice/ipnet#55]
Currently it is not possible to create const item of IpvXNet type, because `Result.unwrap()` is not `const`
It would be great to have a constructor for IpvXNet that allows that. I've prepared two PR with two possible implementations.

#56 First one adds `new_const` method which always checks prefix length at compile time. The drawback is that the syntax is less appealing due to the use of generics:
```
// Both are verified at compile time:
const NET: Ipv4Net = Ipv4Net::new_const::<24>(Ipv4Addr::new(10, 1, 1, 0));
let net = Ipv4Net::new_const::<24>(Ipv4Addr::new(10, 1, 1, 0));
```
#57 Second one adds `new_assert` method which checks prefix length at compile time if called from const context and panics at runtime otherwise:
```
// This code is verified at compile time:
const NET: Ipv4Net = Ipv4Net::new_assert(Ipv4Addr::new(10, 1, 1, 0), 24);
// This code is verified at runtime:
let net = Ipv4Net::new_assert(Ipv4Addr::new(10, 1, 1, 0), 24);
```

**Comment by krisprice** [comment]
Merged and published 2.10.0, thanks!
